name: tuist build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build default scheme
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Tuist
        run: |
          bash <(curl -Ls https://install.tuist.io)
      - name: Setup
        run: |
          ls -lad /usr/local/bin
          ls -la /usr/local/bin/swiftlint
          brew list --formula | grep swift
          whoami
          sudo tuist up
      - name: Build App
        run: |
          tuist build App
      - name: Test
        run: |
          tuist test

